config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :users, except: [:new], path:'usuarios'
  #resources :posts
  resources :searches

  get '/cadastro', to: 'users#new'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  #post '/user_id/:id', to: "user#posting"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/search.rb
class Search < ApplicationRecord
    def users
        @users ||= find_users
    end

    private

    def find_users
        users = User.order(:name)
        users = user.where("name like ?", "%#{keywords}%") if keywords.present?
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts
    validates :password, presence: true, length: { minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

    def create
        @search = Search.create!(params[:search])
        redirect_to @search
    end

    def index
        @users = User.all
    end

    def show
        @search = Search.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :impede_logado,only:[:new]
    before_action :impede_nao_logado, only: [:destroy]

    def new

    end

    def create
        user = User.find_by(email: params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            log_in(user)
            redirect_to user
        else
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_path
    end

    private

    def impede_logado
        if logged_in?
            redirect_to current_user
        end
    end

    def impede_nao_logado
        if !logged_in?
            redirect_to login_path
        end
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :impede_nao_logado, except: [:new, :create]
    before_action :impede_logado, only: [:new]
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            redirect_to @user
        else
            render 'new'
        end
    end

    def index
        @users = User.all
    end

    '''def posting
        @posts = Post.all(post_params)
        if @post.save
            redirect_to root_path
        else
            redirect_to @user
        end
    end'''

    def show
        @user=User.find(params[:id])
    end

    private
    
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def post_params
        params.requite(:post).permit(:content, :user)
    end

    def impede_nao_logado
        if !logged_in?
            redirect_to root_path
        end
    end

    def impede_logado
        if logged_in?
            redirect_to current_user
        end
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            if @current_user.nil?
                @current_user = User.find_by(id: session[:user_id])
            else
                @current_user
            end
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Logins</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= link_to "Sair", logout_path, method: :delete %>
      <%= current_user.name %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/searches/index.html.erb
<h1>Pesquisa!</h1>

<%= form_tag users_path, method: :get do %>
    <p>
        <%= text_field_tag :search, params[:search] %>
        <%= button_tag "Search", name: nil %>
    </p>
<% end %>

<!--div id="names">
     render @users %>
div>-->

app/views/searches/show.html.erb
<h1>Resultados de Pesquisa!</h1>

<%= render @search.users %>

app/views/static_pages/home.html.erb
<h1>Bem-vindo ao nosso site!</h1>

<%= link_to "Cadastre-se agora!", cadastro_path %>
<%= link_to "Logue agora!", login_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

    <div class="field">
        <%= form.label :name, "Nome" %>
        <%= form.text_field :name %>
    </div>

    <div class="field">
        <%= form.label :email, "E-mail" %>
        <%= form.email_field :email %>
    </div>

    <div class="field">
        <%= form.label :password, "Senha" %>
        <%= form.password_field :password %>
    </div>

    <div class="field">
        <%= form.label :password_confirmation, "Confirmar senha" %>
        <%= form.password_field :password_confirmation %>
    </div>

    <div class="actions">
        <%= form.submit "Cadastrar" %>
    </div>

    <% end %>

app/views/users/index.html.erb
<h1>Você está logado!</h1>

<table>
    <% @users.each do |usuario| %>
        <tr>
            <td><%= usuario.name %></td>
            <td></td>
            <td></td>
            <td><%= usuario.email %></td>
        <tr>
    <% end %>
</table>

<%= link_to "Página do Usuário!", login_path %>

app/views/users/new.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Já possui uma conta?", login_path %>

<h1>Cadastre-se!</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p>
    <strong>Nome: </strong> 
    <%= @user.name %>
</p>
<p>
    <strong>E-mail: </strong> 
    <%= @user.email %>
</p>

<!--<% if(@user.id==current_user.id) %>
    <%= form_with(model: @post, local: true) do |form| %>

        <div class="field">
            <%= form.label :content, "Conteúdo: " %>
            <%= form.text_field :content %>
        </div>

        <div class="action">
            <%= form.submit "Postar!" %>
            <%= form.hidden_field :user_id, :value => @user.id%>
        </div>

    <% end %>
<% end %> -->

<table>
    <% if @posts %>
        <% @posts.each do |post| %>
            <% if post.user.id == @user.id %>
                <tr>
                    <td><%= post.Content %></td>
                <tr>
            <% end %>
        <% end %>
    <% end %>
</table>

<%= link_to "Usuários do site", users_path %>